// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int GameState_ba29fb2e6dd3cbc45bd29f3367ed30adIndex = 0;
		public const int Container_11cb97191c21e4e609b0324a7f00b18dIndex = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "GameState_ba29fb2e6dd3cbc45bd29f3367ed30ad", 0 },

			{ "Container_11cb97191c21e4e609b0324a7f00b18d", 1 },

		};
	}
}
