// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Container_11cb97191c21e4e609b0324a7f00b18dIndex = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Container_11cb97191c21e4e609b0324a7f00b18d", 0 },

		};
	}
}
