// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct GameStateHandler_GameStateComponent_2155129602599516921 : ICoherenceComponentData
	{
		public uint currentState;
		public float waitingTimeRemaining;
		public byte[] dummyArray;

		public override string ToString()
		{
			return $"GameStateHandler_GameStateComponent_2155129602599516921(currentState: {currentState}, waitingTimeRemaining: {waitingTimeRemaining}, dummyArray: {dummyArray})";
		}

		public uint GetComponentType() => Definition.InternalGameStateHandler_GameStateComponent_2155129602599516921;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly uint _currentState_Min = 0;
		private static readonly uint _currentState_Max = 4294967295;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (GameStateHandler_GameStateComponent_2155129602599516921)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				currentState = other.currentState;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				waitingTimeRemaining = other.waitingTimeRemaining;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				dummyArray = other.dummyArray;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(GameStateHandler_GameStateComponent_2155129602599516921 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.currentState, _currentState_Min, _currentState_Max, "GameStateHandler_GameStateComponent_2155129602599516921.currentState");
				data.currentState = Coherence.Utils.Bounds.Clamp(data.currentState, _currentState_Min, _currentState_Max);
				bitStream.WriteUIntegerRange(data.currentState, 32, 0);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.waitingTimeRemaining, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBytesList(data.dummyArray);
			}
			mask >>= 1;
		}

		public static (GameStateHandler_GameStateComponent_2155129602599516921, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GameStateHandler_GameStateComponent_2155129602599516921();
	
			if (bitStream.ReadMask())
			{
				val.currentState = bitStream.ReadUIntegerRange(32, 0);
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.waitingTimeRemaining = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.dummyArray = bitStream.ReadBytesList();
				mask |= 0b00000000000000000000000000000100;
			}
			return (val, mask, null);
		}
		public static (GameStateHandler_GameStateComponent_2155129602599516921, uint, uint?) DeserializeArchetypeGameStateHandler_ec2ebf1be19db254da1ba90b22940b35_GameStateHandler_GameStateComponent_2155129602599516921_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GameStateHandler_GameStateComponent_2155129602599516921();
			if (bitStream.ReadMask())
			{
				val.currentState = bitStream.ReadUIntegerRange(32, 0);
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.waitingTimeRemaining = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.dummyArray = bitStream.ReadBytesList();
				mask |= 0b00000000000000000000000000000100;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as GameStateHandler_GameStateComponent_2155129602599516921?;
	
			dummyArray = (mask & 0b00000000000000000000000000000100) != 0 ? last?.dummyArray.CopyOrCloneFrom(dummyArray) : last?.dummyArray;
		}
	}
}